include_guard()

option(GARVIRT_ENABLE_CHECKS "" ${PROJECT_IS_TOP_LEVEL})
option(GARVIRT_ENABLE_CXX_WARN "" ${GARVIRT_ENABLE_CHECKS})
option(GARVIRT_ENABLE_CLANG_TIDY "" ${GARVIRT_ENABLE_CHECKS})
option(GARVIRT_ENABLE_SAN "" ${GARVIRT_ENABLE_CHECKS})
